In [5]:
!pip install pandas

import pandas as pd

171.08s - pydevd: Sending message related to process being replaced timed-out after 5 seconds
Requirement already satisfied: pandas in /Users/test/anaconda3/lib/python3.11/site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/test/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/test/anaconda3/lib/python3.11/site-packages (from pandas) (2022.7)
Collecting numpy>=1.21.0 (from pandas)
  Obtaining dependency information for numpy>=1.21.0 from https://files.pythonhosted.org/packages/e4/04/ff11611200acd602a1e5129e36cfd25bf01ad8e5cf927baf2e90236eb02e/numpy-2.3.4-cp311-cp311-macosx_14_0_arm64.whl.metadata
  Downloading numpy-2.3.4-cp311-cp311-macosx_14_0_arm64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 3.1 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in /Users/test/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Downloading numpy-2.3.4-cp311-cp311-macosx_14_0_arm64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 23.6 MB/s eta 0:00:00a 0:00:01
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tables 3.8.0 requires blosc2~=2.0.0, which is not installed.
tables 3.8.0 requires cython>=0.29.21, which is not installed.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
numba 0.57.0 requires numpy<1.25,>=1.21, but you have numpy 2.3.4 which is incompatible.
scipy 1.10.1 requires numpy<1.27.0,>=1.19.5, but you have numpy 2.3.4 which is incompatible.
Successfully installed numpy-2.3.4

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [6]:
physical_activity_data = pd.read_csv('Physical_Activity.csv')

NameError: name 'pd' is not defined

In [ ]:
physical_activity_data.head()

,SEQN,PAQ706,PAQ605,PAQ610,PAD615,PAQ620,PAQ625,PAD630,PAQ635,PAQ640,...,PAQ650,PAQ655,PAD660,PAQ665,PAQ670,PAD675,PAD680,PAQ710,PAQ715,PAAQUEX
0,62161.0,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,...,2.0,NaN,NaN,2.0,NaN,NaN,300.0,3.0,3.0,1.0
1,62162.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,8.0,1.0
2,62163.0,NaN,2.0,NaN,NaN,2.0,NaN,NaN,1.0,6.0,...,2.0,NaN,NaN,2.0,NaN,NaN,720.0,2.0,3.0,2.0
3,62164.0,NaN,1.0,5.0,60.0,2.0,NaN,NaN,2.0,NaN,...,1.0,5.0,60.0,1.0,1.0,45.0,300.0,2.0,8.0,1.0
4,62165.0,NaN,2.0,NaN,NaN,2.0,NaN,NaN,1.0,7.0,...,1.0,2.0,25.0,1.0,2.0,25.0,600.0,5.0,2.0,2.0

In [ ]:
physical_activity_data.shape

(9107, 21)

In [ ]:
pd.set_option('display.max_columns',100)

In [ ]:
physical_activity_data.head()

,SEQN,PAQ706,PAQ605,PAQ610,PAD615,PAQ620,PAQ625,PAD630,PAQ635,PAQ640,PAD645,PAQ650,PAQ655,PAD660,PAQ665,PAQ670,PAD675,PAD680,PAQ710,PAQ715,PAAQUEX
0,62161.0,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,300.0,3.0,3.0,1.0
1,62162.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,8.0,1.0
2,62163.0,NaN,2.0,NaN,NaN,2.0,NaN,NaN,1.0,6.0,60.0,2.0,NaN,NaN,2.0,NaN,NaN,720.0,2.0,3.0,2.0
3,62164.0,NaN,1.0,5.0,60.0,2.0,NaN,NaN,2.0,NaN,NaN,1.0,5.0,60.0,1.0,1.0,45.0,300.0,2.0,8.0,1.0
4,62165.0,NaN,2.0,NaN,NaN,2.0,NaN,NaN,1.0,7.0,45.0,1.0,2.0,25.0,1.0,2.0,25.0,600.0,5.0,2.0,2.0

In [ ]:
# Dropping all the duplicates records from the dataset, and after deleting the duplicates checking the shape of the dataset by calling shape.
physical_activity_data.drop_duplicates(inplace = True)

In [ ]:
physical_activity_data.shape

(9107, 21)

In [ ]:
# I'm checking the null-values in the dataset. 
physical_activity_data.isnull().sum()

SEQN          0
PAQ706     6807
PAQ605     2328
PAQ610     8160
PAD615     8164
PAQ620     2328
PAQ625     7042
PAD630     7048
PAQ635     2328
PAQ640     6763
PAD645     6767
PAQ650     2328
PAQ655     7198
PAD660     7201
PAQ665     2328
PAQ670     6215
PAD675     6220
PAD680     2334
PAQ710       29
PAQ715       29
PAAQUEX       0
dtype: int64

In [ ]:
# Removing the null values percentage more than 70% columns. 
columns_to_drop = ['PAQ706', 'PAQ610', 'PAD615', 'PAQ625', 'PAD630', 'PAQ640', 'PAD645','PAQ655', 'PAD660', 'PAQ670', 'PAD675', 'PAD645','PAAQUEX','PAQ710','PAQ715','PAQ706','PAD680']

physical_activity_data.drop(columns=columns_to_drop, inplace=True)

In [ ]:
physical_activity_data.isnull().sum()

SEQN         0
PAQ605    2328
PAQ620    2328
PAQ635    2328
PAQ650    2328
PAQ665    2328
dtype: int64

In [ ]:
physical_activity_data = physical_activity_data.dropna()

In [ ]:
physical_activity_data.shape

(6779, 6)

In [ ]:
physical_activity_data.isnull().sum()

SEQN      0
PAQ605    0
PAQ620    0
PAQ635    0
PAQ650    0
PAQ665    0
dtype: int64

In [ ]:
day_data = pd.read_csv('PAXDAY_G.csv')

In [ ]:
day_data.shape

(61168, 15)

In [ ]:
# Defining a function to check if a participant's first and last day valid minutes (PAXTMD) are less than the average valid minutes of the middle days.
def pattern_checker(group):
    # Sorting the group's records by the day of measurement (PAXDAYD)
    group_sorted = group.sort_values(by='PAXDAYD')

    # If there are less than 3 days, we cannot check the pattern (no "middle" days)
    if len(group_sorted) < 3:
        return False

    # Extracting the valid minutes for the first day, last day, and the middle days.
    first_day = group_sorted.iloc[0]['PAXTMD']
    last_day  = group_sorted.iloc[-1]['PAXTMD']
    middle_days = group_sorted.iloc[1:-1]['PAXTMD']

    # Checking if both the first and last day's valid minutes are lower than the average of the middle days.
    return (first_day < middle_days.mean()) and (last_day < middle_days.mean())

In [ ]:
# Applying this function to each participant group in the day dataset (assumed to be in 'day_data').
pattern_series = day_data.groupby('SEQN').apply(pattern_checker)

In [ ]:

# Counting how many participants satisfy the pattern.
pattern_count = pattern_series.sum()
print("Number of participants with the pattern:", pattern_count)

# For additional context, we can also see the distribution of number of days per participant:
days_distribution = day_data.groupby('SEQN').size().value_counts().sort_index()
print("Distribution of days per participant:")
print(days_distribution)

Number of participants with the pattern: 6884
Distribution of days per participant:
1      10
2      23
3      29
4      37
5      48
6      37
7      57
8      68
9    6608
dtype: int64

In [ ]:
day_data.shape

(61168, 15)

In [ ]:
cols_of_interest = ['PAXAISMD', 'PAXVMD', 'PAXMTSD', 'PAXWWMD',
                    'PAXSWMD', 'PAXNWMD', 'PAXUMD', 'PAXLXSD']

# Group the data by SEQN and calculate both mean and standard deviation for these columns.
agg_results = day_data.groupby('SEQN')[cols_of_interest].agg(['mean', 'std'])

# Flatten the MultiIndex columns to a single level with the desired naming convention.
agg_results.columns = [f"{col}_{stat}" for col, stat in agg_results.columns]

# Store the final DataFrame in day_data variable.
day_data = agg_results

# To verify, print the first few rows and column names.
print(day_data.head())
print("Final columns:", list(day_data.columns))

         PAXAISMD_mean  PAXAISMD_std  PAXVMD_mean  PAXVMD_std  PAXMTSD_mean  \
SEQN
62161.0   2.949179e+06  7.099625e+05  1281.111111  315.770662  10702.718222
62163.0   2.342750e+06  1.210420e+06  1279.333333  356.265351  13116.369667
62164.0   2.541249e+06  7.536726e+05  1281.000000  315.977056  11624.051000
62165.0   2.409771e+06  9.617983e+05  1281.111111  315.770662  18516.184778
62166.0   2.092003e+06  8.591190e+05  1123.600000  419.992024  16514.951400

         PAXMTSD_std  PAXWWMD_mean  PAXWWMD_std  PAXSWMD_mean  PAXSWMD_std  \
SEQN
62161.0  5558.563548    733.888889   308.413863    388.888889   205.754371
62163.0  7252.090094    805.111111   334.380937    375.888889   181.596699
62164.0  4182.303206    818.777778   282.408736    373.111111   164.884387
62165.0  6788.305624    840.888889   226.521767    379.000000   199.953745
62166.0  8930.245537    724.600000   322.422549    373.800000   155.995833

         PAXNWMD_mean  PAXNWMD_std  PAXUMD_mean  PAXUMD_std   PAXLXSD_mean  \
SEQN
62161.0    102.111111   252.250096    56.222222   24.782947  279407.576667
62163.0     53.888889   161.666667    44.444444   22.198599   58824.407778
62164.0     22.555556    67.666667    66.555556   28.535553   27941.847778
62165.0     25.111111    75.333333    36.111111   16.127961  183071.191111
62166.0      0.000000     0.000000    25.200000   10.497619  278502.366000

           PAXLXSD_std
SEQN
62161.0  286575.124072
62163.0   83758.331335
62164.0   33143.728082
62165.0  122363.155791
62166.0  145220.691099
Final columns: ['PAXAISMD_mean', 'PAXAISMD_std', 'PAXVMD_mean', 'PAXVMD_std', 'PAXMTSD_mean', 'PAXMTSD_std', 'PAXWWMD_mean', 'PAXWWMD_std', 'PAXSWMD_mean', 'PAXSWMD_std', 'PAXNWMD_mean', 'PAXNWMD_std', 'PAXUMD_mean', 'PAXUMD_std', 'PAXLXSD_mean', 'PAXLXSD_std']

In [ ]:
day_data.shape

(6917, 16)

In [ ]:
day_data.isnull().sum()

PAXAISMD_mean     0
PAXAISMD_std     10
PAXVMD_mean       0
PAXVMD_std       10
PAXMTSD_mean      0
PAXMTSD_std      10
PAXWWMD_mean      0
PAXWWMD_std      10
PAXSWMD_mean      0
PAXSWMD_std      10
PAXNWMD_mean      0
PAXNWMD_std      10
PAXUMD_mean       0
PAXUMD_std       10
PAXLXSD_mean      0
PAXLXSD_std      10
dtype: int64

In [ ]:
day_data.dropna(inplace= True)

In [ ]:
day_data.isnull().sum()

PAXAISMD_mean    0
PAXAISMD_std     0
PAXVMD_mean      0
PAXVMD_std       0
PAXMTSD_mean     0
PAXMTSD_std      0
PAXWWMD_mean     0
PAXWWMD_std      0
PAXSWMD_mean     0
PAXSWMD_std      0
PAXNWMD_mean     0
PAXNWMD_std      0
PAXUMD_mean      0
PAXUMD_std       0
PAXLXSD_mean     0
PAXLXSD_std      0
dtype: int64

In [ ]:
day_data.shape

(6907, 16)

In [ ]:
demo_data = pd.read_csv('demo.csv')

In [ ]:
demo_data.shape

(9756, 48)

In [ ]:
columns_to_drop = [

    'RIDAGEMN',  # Age in months (only for infants, we use RIDAGEYR instead)
    'RIDRETH3',  # Alternative version of race/ethnicity (keeping RIDRETH1)

    'DMDHHSZA',  # Number of children under 5
    'DMDHHSZB',  # Number of children aged 6-17
    'DMDHHSZE',  # Number of adults aged 60+

    'DMDHRMAR',  # Marital status (not directly impacting activity/sleep)
    'DMQMILIZ',  # Military service
    'DMQADFC',  # Served in a foreign country
    'DMDCITZN',  # Citizenship status (we keep DMDBORN4 instead)

    'RIDSTATR',  # Interview/Exam status
    'SIALANG',  # Interview language
    'SIAPROXY',  # Proxy respondent used
    'SIAINTRP',  # Interpreter used

    'DMDHRGND',  # Gender of household reference person
    'DMDHREDZ',  # Education level of reference person (duplicate of DMDHREDU)

    'DMDFMSIZ',  # Total number in the family (we are keeping DMDHHSIZ instead)
    'INDHHINC',  # Alternative income measure (keeping INDHHIN2 instead)
    'INDFMINC',  # Alternative income measure (keeping INDFMPIR instead)

    'INDFMPIR2',
    'INDFMIN2',

    'DMDHRAGE', 'DMDEDUC3', 'DMDEDUC2', 'DMQADFC', 'DMDHRYRS',
    'DMDHHRSD', 'DMDHHRRD', 'DMDHRDYS', 'DMDHHRSD', 'DMDHHRSE',
    'DMDBRTHD', 'DMDBRTHM', 'DMDBRTHY', 'DMDBORN', 'DMDYRSUS',
    'DMDIMARM', 'DMDHRRES', 'DMDHHRRP'
]

In [ ]:
demo_data = demo_data.drop(columns=columns_to_drop, errors = 'ignore')

In [ ]:
demo_data = demo_data.drop(columns = ['SDDSRVYR','RIDRETH1','RIDEXMON','RIDEXMON','RIDEXAGM','DMDMARTL','DMDMARTL','FIALANG',
       'FIAPROXY', 'FIAINTRP', 'MIALANG', 'MIAPROXY', 'MIAINTRP', 'AIALANGA',
       'WTINT2YR', 'WTMEC2YR', 'SDMVPSU', 'SDMVSTRA','DMDHRBR4','DMDHSEDU','RIDEXAGY','RIDEXPRG','INDFMPIR'], errors ='ignore' )

In [ ]:
demo_data.shape

(9756, 7)

In [ ]:
# For INDHHIN2: Replace 77, 99, and missing values with 16
demo_data['INDHHIN2'] = pd.to_numeric(demo_data['INDHHIN2'], errors='coerce')
demo_data['INDHHIN2'] = demo_data['INDHHIN2'].replace([77, 99], 16)
demo_data['INDHHIN2'] = demo_data['INDHHIN2'].fillna(16)



# For DMDHREDU: Replace 7, 8, 9, and missing values with 6
demo_data['DMDHREDU'] = pd.to_numeric(demo_data['DMDHREDU'], errors='coerce')
demo_data['DMDHREDU'] = demo_data['DMDHREDU'].replace([7, 8, 9], 6)
demo_data['DMDHREDU'] = demo_data['DMDHREDU'].fillna(6)

In [ ]:
demo_data.shape

(9756, 7)

In [ ]:
print(demo_data.shape)
print(day_data.shape)
print(physical_activity_data.shape)

(9756, 7)
(6907, 16)
(6779, 6)

In [ ]:
merged_data = day_data.merge(physical_activity_data, on = 'SEQN', how = 'inner')

In [ ]:
merged_data.shape

(5741, 22)

In [ ]:
merged_data.drop( columns = ['PAXAISMD_mean','PAXAISMD_std','PAXVMD_mean','PAXVMD_std','PAXUMD_mean','PAXUMD_std','PAXLXSD_mean','PAXLXSD_std'], inplace = True)

In [ ]:
merged_data.shape

(5741, 14)

In [ ]:
merged_data = merged_data.merge(demo_data, on = 'SEQN', how = 'inner')

In [ ]:
merged_data.shape

(5741, 20)

In [ ]:
merged_data.isnull().sum()

SEQN            0
PAXMTSD_mean    0
PAXMTSD_std     0
PAXWWMD_mean    0
PAXWWMD_std     0
PAXSWMD_mean    0
PAXSWMD_std     0
PAXNWMD_mean    0
PAXNWMD_std     0
PAQ605          0
PAQ620          0
PAQ635          0
PAQ650          0
PAQ665          0
RIAGENDR        0
RIDAGEYR        0
DMDBORN4        0
INDHHIN2        0
DMDHHSIZ        0
DMDHREDU        0
dtype: int64

In [ ]:
%store merged_data

Stored 'merged_data' (DataFrame)

In [ ]:
health_status = pd.read_csv('HSQ.csv')

In [ ]:
health_status.drop( columns=['HSQ480', 'HSQ490', 'HSQ493', 'HSQ496', 'HSQ500', 'HSQ510',
       'HSQ520', 'HSQ571', 'HSQ580', 'HSQ590','HSAQUEX'] , inplace = True )

In [ ]:
health_status.shape

(8956, 3)

In [ ]:
total_data = pd.merge(merged_data, health_status, on = 'SEQN', how='inner')

In [ ]:
total_data.isnull().sum()

SEQN              0
PAXMTSD_mean      0
PAXMTSD_std       0
PAXWWMD_mean      0
PAXWWMD_std       0
PAXSWMD_mean      0
PAXSWMD_std       0
PAXNWMD_mean      0
PAXNWMD_std       0
PAQ605            0
PAQ620            0
PAQ635            0
PAQ650            0
PAQ665            0
RIAGENDR          0
RIDAGEYR          0
DMDBORN4          0
INDHHIN2          0
DMDHHSIZ          0
DMDHREDU          0
HSD010          410
HSQ470          410
dtype: int64

In [ ]:
total_data.shape

(5741, 22)

In [ ]:
total_data.head()

,SEQN,PAXMTSD_mean,PAXMTSD_std,PAXWWMD_mean,PAXWWMD_std,PAXSWMD_mean,PAXSWMD_std,PAXNWMD_mean,PAXNWMD_std,PAQ605,PAQ620,PAQ635,PAQ650,PAQ665,RIAGENDR,RIDAGEYR,DMDBORN4,INDHHIN2,DMDHHSIZ,DMDHREDU,HSD010,HSQ470
0,62161.0,10702.718222,5558.563548,733.888889,308.413863,388.888889,205.754371,102.111111,252.250096,2.0,2.0,2.0,2.0,2.0,1.0,22.0,1.0,14.0,5.0,5.0,3.0,5.397605e-79
1,62163.0,13116.369667,7252.090094,805.111111,334.380937,375.888889,181.596699,53.888889,161.666667,2.0,2.0,1.0,2.0,2.0,1.0,14.0,1.0,15.0,5.0,5.0,3.0,5.397605e-79
2,62164.0,11624.051000,4182.303206,818.777778,282.408736,373.111111,164.884387,22.555556,67.666667,1.0,2.0,2.0,1.0,1.0,2.0,44.0,1.0,8.0,5.0,4.0,NaN,NaN
3,62165.0,18516.184778,6788.305624,840.888889,226.521767,379.000000,199.953745,25.111111,75.333333,2.0,2.0,1.0,1.0,1.0,2.0,14.0,1.0,4.0,5.0,2.0,4.0,5.000000e+00
4,62169.0,8893.430667,3980.224218,817.333333,279.022849,383.777778,158.229088,7.888889,23.666667,2.0,2.0,2.0,2.0,2.0,1.0,21.0,1.0,2.0,5.0,1.0,3.0,1.000000e+01

In [ ]:
total_data.dropna(inplace= True)

In [ ]:
total_data.shape

(5331, 22)

In [ ]:
total_data.head()

,SEQN,PAXMTSD_mean,PAXMTSD_std,PAXWWMD_mean,PAXWWMD_std,PAXSWMD_mean,PAXSWMD_std,PAXNWMD_mean,PAXNWMD_std,PAQ605,PAQ620,PAQ635,PAQ650,PAQ665,RIAGENDR,RIDAGEYR,DMDBORN4,INDHHIN2,DMDHHSIZ,DMDHREDU,HSD010,HSQ470
0,62161.0,10702.718222,5558.563548,733.888889,308.413863,388.888889,205.754371,102.111111,252.250096,2.0,2.0,2.0,2.0,2.0,1.0,22.0,1.0,14.0,5.0,5.0,3.0,5.397605e-79
1,62163.0,13116.369667,7252.090094,805.111111,334.380937,375.888889,181.596699,53.888889,161.666667,2.0,2.0,1.0,2.0,2.0,1.0,14.0,1.0,15.0,5.0,5.0,3.0,5.397605e-79
3,62165.0,18516.184778,6788.305624,840.888889,226.521767,379.000000,199.953745,25.111111,75.333333,2.0,2.0,1.0,1.0,1.0,2.0,14.0,1.0,4.0,5.0,2.0,4.0,5.000000e+00
4,62169.0,8893.430667,3980.224218,817.333333,279.022849,383.777778,158.229088,7.888889,23.666667,2.0,2.0,2.0,2.0,2.0,1.0,21.0,1.0,2.0,5.0,1.0,3.0,1.000000e+01
5,62170.0,8982.683889,4902.074180,744.222222,238.749753,441.777778,222.475717,30.555556,91.666667,2.0,1.0,2.0,1.0,2.0,1.0,15.0,1.0,15.0,4.0,5.0,2.0,9.000000e+00

In [ ]:
total_data.isnull().sum()

SEQN            0
PAXMTSD_mean    0
PAXMTSD_std     0
PAXWWMD_mean    0
PAXWWMD_std     0
PAXSWMD_mean    0
PAXSWMD_std     0
PAXNWMD_mean    0
PAXNWMD_std     0
PAQ605          0
PAQ620          0
PAQ635          0
PAQ650          0
PAQ665          0
RIAGENDR        0
RIDAGEYR        0
DMDBORN4        0
INDHHIN2        0
DMDHHSIZ        0
DMDHREDU        0
HSD010          0
HSQ470          0
dtype: int64

In [ ]:
med_dis_data = pd.read_csv('med_dis_data.csv')

In [ ]:
med_dis_data.drop(columns= ['MCQ010', 'MCQ025', 'MCQ035', 'MCQ040', 'MCQ050', 'MCQ051',
       'MCQ053', 'MCQ070', 'MCQ075', 'MCQ080', 'MCQ082', 'MCQ084', 'MCQ086',
       'MCQ092', 'MCD093', 'MCQ140', 'MCQ149', 'MCQ180A', 'MCQ195',
       'MCQ160N', 'MCQ180N', 'MCQ160B', 'MCQ180B', 'MCQ160C', 'MCQ180C',
       'MCQ160D', 'MCQ180D', 'MCQ160E', 'MCQ180E', 'MCQ160F', 'MCQ180F',
       'MCQ160G', 'MCQ180G', 'MCQ160M', 'MCQ170M', 'MCQ180M', 'MCQ160K',
       'MCQ170K', 'MCQ180K', 'MCQ160L', 'MCQ170L', 'MCQ180L', 'MCQ220',
       'MCQ230A', 'MCQ230B', 'MCQ230C', 'MCQ230D', 'MCQ240A', 'MCQ240AA',
       'MCQ240B', 'MCQ240BB', 'MCQ240C', 'MCQ240CC', 'MCQ240D', 'MCQ240DD',
       'MCQ240DK', 'MCQ240E', 'MCQ240F', 'MCQ240G', 'MCQ240H', 'MCQ240I',
       'MCQ240J', 'MCQ240K', 'MCQ240L', 'MCQ240M', 'MCQ240N', 'MCQ240O',
       'MCQ240P', 'MCQ240Q', 'MCQ240R', 'MCQ240S', 'MCQ240T', 'MCQ240U',
       'MCQ240V', 'MCQ240W', 'MCQ240X', 'MCQ240Y', 'MCQ240Z', 'MCQ300A',
       'MCQ300B', 'MCQ300C', 'MCQ365C', 'MCQ365D',
       'MCQ370C', 'MCQ370D', 'MCQ380'], inplace= True)

In [ ]:
med_dis_data.head()

      SEQN  MCQ160A  MCQ365A  MCQ365B  MCQ370A  MCQ370B
0  62161.0      2.0      1.0      2.0      1.0      1.0
1  62162.0      NaN      NaN      NaN      NaN      NaN
2  62163.0      NaN      NaN      NaN      NaN      NaN
3  62164.0      2.0      2.0      2.0      1.0      1.0
4  62165.0      NaN      NaN      NaN      NaN      NaN

In [ ]:
total_data = total_data.merge(med_dis_data, on = 'SEQN', how = 'inner')

In [ ]:
total_data.shape

(5331, 27)

In [ ]:
total_data.isnull().sum()

SEQN               0
PAXMTSD_mean       0
PAXMTSD_std        0
PAXWWMD_mean       0
PAXWWMD_std        0
PAXSWMD_mean       0
PAXSWMD_std        0
PAXNWMD_mean       0
PAXNWMD_std        0
PAQ605             0
PAQ620             0
PAQ635             0
PAQ650             0
PAQ665             0
RIAGENDR           0
RIDAGEYR           0
DMDBORN4           0
INDHHIN2           0
DMDHHSIZ           0
DMDHREDU           0
HSD010             0
HSQ470             0
MCQ160A         1077
MCQ365A          550
MCQ365B          550
MCQ370A          550
MCQ370B          550
dtype: int64

In [ ]:
total_data.dropna(inplace= True)

In [ ]:
total_data.isnull().sum()

SEQN            0
PAXMTSD_mean    0
PAXMTSD_std     0
PAXWWMD_mean    0
PAXWWMD_std     0
PAXSWMD_mean    0
PAXSWMD_std     0
PAXNWMD_mean    0
PAXNWMD_std     0
PAQ605          0
PAQ620          0
PAQ635          0
PAQ650          0
PAQ665          0
RIAGENDR        0
RIDAGEYR        0
DMDBORN4        0
INDHHIN2        0
DMDHHSIZ        0
DMDHREDU        0
HSD010          0
HSQ470          0
MCQ160A         0
MCQ365A         0
MCQ365B         0
MCQ370A         0
MCQ370B         0
dtype: int64

In [ ]:
total_data.shape

(4254, 27)

In [ ]:
total_data['PAQ605'] = total_data['PAQ605'].replace({2:1,1:0})
total_data['PAQ620'] = total_data['PAQ620'].replace({2:1,1:0})
total_data['PAQ635'] = total_data['PAQ635'].replace({2:1,1:0})
total_data['PAQ650'] = total_data['PAQ650'].replace({2:1,1:0})
total_data['PAQ665'] = total_data['PAQ665'].replace({2:1,1:0})
total_data['MCQ160A'] = total_data['MCQ160A'].replace({2:0,1:1})
total_data['MCQ365A'] = total_data['MCQ365A'].replace({2:0,1:1})
total_data['MCQ365B'] = total_data['MCQ365B'].replace({2:0,1:1})
total_data['MCQ370A'] = total_data['MCQ370A'].replace({2:0,1:1})
total_data['MCQ370B'] = total_data['MCQ370B'].replace({2:0,1:1})
total_data['RIAGENDR'] = total_data['RIAGENDR'].replace({2:1,1:0})
total_data['DMDBORN4'] = total_data['DMDBORN4'].replace({2:1,1:0})
total_data['HSD010'] = total_data['HSD010'].replace([1, 2, 3], 0).replace([4, 5], 1)
total_data['INDHHIN2'] = total_data['INDHHIN2'].replace([1,2,3,4,13],1).replace([5,6,7],2).replace([8,9,10],3).replace([14,15],4).replace([12],5)
total_data['DMDHHSIZ'] = total_data['DMDHHSIZ'].replace([2,3,4],2).replace([5,6,7],3)

In [ ]:
total_data.drop( columns = ['HSQ470'], inplace = True )

In [ ]:
total_data.head(20)

,SEQN,PAXMTSD_mean,PAXMTSD_std,PAXWWMD_mean,PAXWWMD_std,PAXSWMD_mean,PAXSWMD_std,PAXNWMD_mean,PAXNWMD_std,PAQ605,PAQ620,PAQ635,PAQ650,PAQ665,RIAGENDR,RIDAGEYR,DMDBORN4,INDHHIN2,DMDHHSIZ,DMDHREDU,HSD010,MCQ160A,MCQ365A,MCQ365B,MCQ370A,MCQ370B
0,62161.0,10702.718222,5558.563548,733.888889,308.413863,388.888889,205.754371,102.111111,252.250096,1.0,1.0,1.0,1.0,1.0,0.0,22.0,0.0,4.0,3.0,5.0,0.0,0.0,1.0,0.0,1.0,1.0
3,62169.0,8893.430667,3980.224218,817.333333,279.022849,383.777778,158.229088,7.888889,23.666667,1.0,1.0,1.0,1.0,1.0,0.0,21.0,0.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6,62172.0,2552.998000,3791.624514,136.111111,207.170488,105.555556,170.955485,1025.444444,534.966847,1.0,1.0,1.0,1.0,1.0,1.0,43.0,0.0,2.0,1.0,3.0,0.0,0.0,0.0,0.0,1.0,1.0
7,62174.0,7157.632778,3737.068057,713.444444,332.195391,380.444444,199.968817,126.444444,350.682945,1.0,1.0,1.0,1.0,1.0,0.0,80.0,0.0,3.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0
8,62178.0,6551.497556,2129.729791,632.777778,213.616934,551.222222,167.822658,26.222222,78.666667,1.0,1.0,1.0,1.0,1.0,0.0,80.0,0.0,1.0,1.0,3.0,1.0,1.0,0.0,0.0,0.0,1.0
9,62179.0,5681.822500,1765.332384,428.000000,239.002092,235.500000,164.755880,0.000000,0.000000,1.0,1.0,0.0,1.0,1.0,0.0,55.0,0.0,4.0,2.0,5.0,0.0,0.0,0.0,1.0,1.0,0.0
10,62180.0,11616.198444,5399.015617,772.777778,348.542959,403.222222,142.729445,58.666667,176.000000,1.0,1.0,1.0,1.0,1.0,0.0,35.0,0.0,2.0,2.0,5.0,0.0,0.0,0.0,0.0,1.0,0.0
11,62184.0,12185.490333,3796.955736,838.000000,228.058107,394.888889,156.896817,1.222222,3.666667,0.0,1.0,1.0,0.0,1.0,0.0,26.0,0.0,4.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0
13,62189.0,15282.661444,5932.221775,855.444444,310.951809,297.444444,144.245547,99.222222,183.663944,1.0,0.0,1.0,1.0,1.0,1.0,30.0,0.0,3.0,2.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0
15,62191.0,6287.154111,2520.143523,643.888889,244.478754,558.444444,172.361619,18.555556,55.666667,1.0,1.0,1.0,1.0,0.0,0.0,70.0,0.0,4.0,2.0,6.0,0.0,0.0,0.0,0.0,1.0,0.0
18,62199.0,12313.743333,5286.538171,776.888889,316.537298,439.333333,102.099216,26.666667,80.000000,0.0,0.0,0.0,1.0,0.0,0.0,57.0,0.0,4.0,2.0,5.0,0.0,0.0,0.0,0.0,1.0,1.0
19,62200.0,11179.659000,6150.288877,621.333333,283.549819,57.222222,51.688436,572.222222,264.155625,1.0,1.0,1.0,0.0,0.0,0.0,42.0,1.0,4.0,3.0,5.0,0.0,0.0,1.0,1.0,1.0,1.0
20,62202.0,13318.129333,6752.312202,758.111111,325.561225,433.000000,156.356963,39.222222,117.666667,0.0,0.0,1.0,1.0,0.0,0.0,36.0,0.0,4.0,3.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0
21,62205.0,6627.124222,4185.114017,544.777778,333.366457,264.111111,255.043842,407.555556,392.300940,1.0,0.0,0.0,1.0,0.0,0.0,28.0,0.0,4.0,2.0,5.0,0.0,0.0,1.0,0.0,0.0,0.0
22,62208.0,12873.154333,7548.818403,786.333333,422.856654,251.888889,164.100156,199.000000,401.343992,1.0,1.0,1.0,1.0,0.0,0.0,38.0,1.0,2.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
23,62209.0,12315.561000,4041.338709,859.222222,289.066938,364.888889,153.682664,24.555556,73.666667,1.0,1.0,0.0,1.0,1.0,1.0,62.0,1.0,2.0,3.0,2.0,1.0,1.0,0.0,0.0,1.0,1.0
25,62214.0,8829.169556,4868.218634,574.555556,308.531243,525.888889,382.275243,153.666667,353.903235,1.0,1.0,1.0,1.0,1.0,1.0,22.0,0.0,2.0,3.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0
26,62215.0,13966.214333,6456.378044,780.666667,333.589943,357.777778,171.492549,104.333333,231.033547,1.0,1.0,1.0,1.0,1.0,1.0,65.0,0.0,1.0,2.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0
27,62217.0,12118.276000,3903.646207,778.666667,247.405032,433.000000,150.382845,18.333333,55.000000,1.0,1.0,1.0,1.0,0.0,1.0,77.0,0.0,1.0,2.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0
28,62218.0,8400.728889,5111.103631,566.888889,349.723978,310.111111,239.803797,368.555556,468.678224,1.0,0.0,1.0,1.0,1.0,1.0,38.0,0.0,4.0,2.0,2.0,0.0,0.0,1.0,1.0,0.0,1.0

In [ ]:
cols_to_standardize = ['PAXMTSD_mean', 'PAXMTSD_std', 'PAXSWMD_mean', 'PAXSWMD_std','PAXNWMD_mean','PAXNWMD_std','PAXWWMD_mean','PAXWWMD_std']

In [ ]:
print(total_data[cols_to_standardize].describe())

       PAXMTSD_mean   PAXMTSD_std  PAXSWMD_mean  PAXSWMD_std  PAXNWMD_mean  \
count   4254.000000   4254.000000   4254.000000  4254.000000   4254.000000
mean   10354.676329   4860.991037    386.886005   176.321046    130.174132
std     3540.652588   1834.522056    120.602974    67.272797    213.793082
min        2.722444      3.624971      0.000000     0.000000      0.000000
25%     8124.874611   3654.031736    333.111111   137.234672     21.361111
50%    10411.612667   4731.365081    391.555556   165.345009     53.555556
75%    12649.835528   5930.030579    452.000000   202.158291    132.222222
max    29613.147667  20384.885295   1111.888889   677.791450   1281.111111

       PAXNWMD_std  PAXWWMD_mean  PAXWWMD_std
count  4254.000000   4254.000000  4254.000000
mean    178.196097    706.898917   306.535132
std     150.654836    159.693492    68.607072
min       0.000000      0.000000     0.000000
25%      61.666667    657.722222   267.236591
50%     143.333333    742.222222   309.590607
75%     264.000000    805.333333   348.831392
max     717.588690   1173.444444   640.016037

In [ ]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Fit the scaler to the data and transform the specified columns
# This updates the columns in-place
total_data[cols_to_standardize] = scaler.fit_transform(total_data[cols_to_standardize])

# Check the standardized values
print(total_data[cols_to_standardize].describe())

       PAXMTSD_mean   PAXMTSD_std  PAXSWMD_mean   PAXSWMD_std  PAXNWMD_mean  \
count  4.254000e+03  4.254000e+03  4.254000e+03  4.254000e+03  4.254000e+03
mean  -5.278061e-17 -1.896305e-16 -4.295785e-17  1.990520e-16  1.132407e-16
std    1.000118e+00  1.000118e+00  1.000118e+00  1.000118e+00  1.000118e+00
min   -2.924085e+00 -2.648067e+00 -3.208308e+00 -2.621294e+00 -6.089506e-01
25%   -6.298454e-01 -6.579922e-01 -4.459361e-01 -5.810814e-01 -5.090240e-01
50%    1.608264e-02 -7.066756e-02  3.872292e-02 -1.631763e-01 -3.584194e-01
75%    6.483068e-01  5.828031e-01  5.399672e-01  3.841119e-01  9.580904e-03
max    5.439883e+00  8.463087e+00  6.012191e+00  7.455158e+00  5.384048e+00

        PAXNWMD_std  PAXWWMD_mean   PAXWWMD_std
count  4.254000e+03  4.254000e+03  4.254000e+03
mean  -1.765552e-16 -3.234627e-16 -2.514966e-16
std    1.000118e+00  1.000118e+00  1.000118e+00
min   -1.182949e+00 -4.427119e+00 -4.468507e+00
25%   -7.735771e-01 -3.079805e-01 -5.728733e-01
50%   -2.314354e-01  2.212204e-01  4.454109e-02
75%    5.696066e-01  6.164684e-01  6.165725e-01
max    3.580741e+00  2.921850e+00  4.861308e+00

In [ ]:
total_data[cols_to_standardize] = total_data[cols_to_standardize].round(3)

In [ ]:
total_data.head(20)

,SEQN,PAXMTSD_mean,PAXMTSD_std,PAXWWMD_mean,PAXWWMD_std,PAXSWMD_mean,PAXSWMD_std,PAXNWMD_mean,PAXNWMD_std,PAQ605,PAQ620,PAQ635,PAQ650,PAQ665,RIAGENDR,RIDAGEYR,DMDBORN4,INDHHIN2,DMDHHSIZ,DMDHREDU,HSD010,MCQ160A,MCQ365A,MCQ365B,MCQ370A,MCQ370B
0,62161.0,0.098,0.380,0.169,0.027,0.017,0.438,-0.131,0.492,1.0,1.0,1.0,1.0,1.0,0.0,22.0,0.0,4.0,3.0,5.0,0.0,0.0,1.0,0.0,1.0,1.0
3,62169.0,-0.413,-0.480,0.692,-0.401,-0.026,-0.269,-0.572,-1.026,1.0,1.0,1.0,1.0,1.0,0.0,21.0,0.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6,62172.0,-2.204,-0.583,-3.575,-1.448,-2.333,-0.080,4.188,2.368,1.0,1.0,1.0,1.0,1.0,1.0,43.0,0.0,2.0,1.0,3.0,0.0,0.0,0.0,0.0,1.0,1.0
7,62174.0,-0.903,-0.613,0.041,0.374,-0.053,0.352,-0.017,1.145,1.0,1.0,1.0,1.0,1.0,0.0,80.0,0.0,3.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0
8,62178.0,-1.074,-1.489,-0.464,-1.355,1.363,-0.126,-0.486,-0.661,1.0,1.0,1.0,1.0,1.0,0.0,80.0,0.0,1.0,1.0,3.0,1.0,1.0,0.0,0.0,0.0,1.0
9,62179.0,-1.320,-1.688,-1.747,-0.984,-1.255,-0.172,-0.609,-1.183,1.0,1.0,0.0,1.0,1.0,0.0,55.0,0.0,4.0,2.0,5.0,0.0,0.0,0.0,1.0,1.0,0.0
10,62180.0,0.356,0.293,0.413,0.612,0.135,-0.499,-0.335,-0.015,1.0,1.0,1.0,1.0,1.0,0.0,35.0,0.0,2.0,2.0,5.0,0.0,0.0,0.0,0.0,1.0,0.0
11,62184.0,0.517,-0.580,0.821,-1.144,0.066,-0.289,-0.603,-1.159,0.0,1.0,1.0,0.0,1.0,0.0,26.0,0.0,4.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0
13,62189.0,1.392,0.584,0.930,0.064,-0.742,-0.477,-0.145,0.036,1.0,0.0,1.0,1.0,1.0,1.0,30.0,0.0,3.0,2.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0
15,62191.0,-1.149,-1.276,-0.395,-0.905,1.423,-0.059,-0.522,-0.813,1.0,1.0,1.0,1.0,0.0,0.0,70.0,0.0,4.0,2.0,6.0,0.0,0.0,0.0,0.0,1.0,0.0
18,62199.0,0.553,0.232,0.438,0.146,0.435,-1.103,-0.484,-0.652,0.0,0.0,0.0,1.0,0.0,0.0,57.0,0.0,4.0,2.0,5.0,0.0,0.0,0.0,0.0,1.0,1.0
19,62200.0,0.233,0.703,-0.536,-0.335,-2.734,-1.853,2.068,0.571,1.0,1.0,1.0,0.0,0.0,0.0,42.0,1.0,4.0,3.0,5.0,0.0,0.0,1.0,1.0,1.0,1.0
20,62202.0,0.837,1.031,0.321,0.277,0.382,-0.297,-0.425,-0.402,0.0,0.0,1.0,1.0,0.0,0.0,36.0,0.0,4.0,3.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0
21,62205.0,-1.053,-0.368,-1.015,0.391,-1.018,1.170,1.298,1.421,1.0,0.0,0.0,1.0,0.0,0.0,28.0,0.0,4.0,2.0,5.0,0.0,0.0,1.0,0.0,0.0,0.0
22,62208.0,0.711,1.465,0.497,1.696,-1.119,-0.182,0.322,1.481,1.0,1.0,1.0,1.0,0.0,0.0,38.0,1.0,2.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
23,62209.0,0.554,-0.447,0.954,-0.255,-0.182,-0.337,-0.494,-0.694,1.0,1.0,0.0,1.0,1.0,1.0,62.0,1.0,2.0,3.0,2.0,1.0,1.0,0.0,0.0,1.0,1.0
25,62214.0,-0.431,0.004,-0.829,0.029,1.153,3.062,0.110,1.166,1.0,1.0,1.0,1.0,1.0,1.0,22.0,0.0,2.0,3.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0
26,62215.0,1.020,0.870,0.462,0.394,-0.241,-0.072,-0.121,0.351,1.0,1.0,1.0,1.0,1.0,1.0,65.0,0.0,1.0,2.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0
27,62217.0,0.498,-0.522,0.449,-0.862,0.382,-0.386,-0.523,-0.818,1.0,1.0,1.0,1.0,0.0,1.0,77.0,0.0,1.0,2.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0
28,62218.0,-0.552,0.136,-0.877,0.630,-0.637,0.944,1.115,1.928,1.0,0.0,1.0,1.0,1.0,1.0,38.0,0.0,4.0,2.0,2.0,0.0,0.0,1.0,1.0,0.0,1.0

In [ ]:
new_column_names = ['SEQN','PA_mean','PA_std','WW_mean','WW_std','SW_mean','SW_std','NW_mean','NW_std','VWA','MWA','W/B','VRC','MRC','Gender','Age','US_born','HH_Income','HH_size','Edu_level','Health_status','Arthritis','Lose_weight','Excercise','Con_lost_weight','increase_exercise']

In [ ]:
total_data.columns = new_column_names

In [ ]:
total_data.dtypes

SEQN                 float64
PA_mean              float64
PA_std               float64
WW_mean              float64
WW_std               float64
SW_mean              float64
SW_std               float64
NW_mean              float64
NW_std               float64
VWA                  float64
MWA                  float64
W/B                  float64
VRC                  float64
MRC                  float64
Gender               float64
Age                  float64
US_born              float64
HH_Income            float64
HH_size              float64
Edu_level            float64
Health_status        float64
Arthritis            float64
Lose_weight          float64
Excercise            float64
Con_lost_weight      float64
increase_exercise    float64
dtype: object

In [ ]:
total_data.drop (columns= 'SEQN', inplace= True)

In [79]:
total_data.shape

(4254, 25)

In [80]:
total_data.head(20)

,PA_mean,PA_std,WW_mean,WW_std,SW_mean,SW_std,NW_mean,NW_std,VWA,MWA,W/B,VRC,MRC,Gender,Age,US_born,HH_Income,HH_size,Edu_level,Health_status,Arthritis,Lose_weight,Excercise,Con_lost_weight,increase_exercise
0,0.098,0.380,0.169,0.027,0.017,0.438,-0.131,0.492,1.0,1.0,1.0,1.0,1.0,0.0,22.0,0.0,4.0,3.0,5.0,0.0,0.0,1.0,0.0,1.0,1.0
3,-0.413,-0.480,0.692,-0.401,-0.026,-0.269,-0.572,-1.026,1.0,1.0,1.0,1.0,1.0,0.0,21.0,0.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6,-2.204,-0.583,-3.575,-1.448,-2.333,-0.080,4.188,2.368,1.0,1.0,1.0,1.0,1.0,1.0,43.0,0.0,2.0,1.0,3.0,0.0,0.0,0.0,0.0,1.0,1.0
7,-0.903,-0.613,0.041,0.374,-0.053,0.352,-0.017,1.145,1.0,1.0,1.0,1.0,1.0,0.0,80.0,0.0,3.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0
8,-1.074,-1.489,-0.464,-1.355,1.363,-0.126,-0.486,-0.661,1.0,1.0,1.0,1.0,1.0,0.0,80.0,0.0,1.0,1.0,3.0,1.0,1.0,0.0,0.0,0.0,1.0
9,-1.320,-1.688,-1.747,-0.984,-1.255,-0.172,-0.609,-1.183,1.0,1.0,0.0,1.0,1.0,0.0,55.0,0.0,4.0,2.0,5.0,0.0,0.0,0.0,1.0,1.0,0.0
10,0.356,0.293,0.413,0.612,0.135,-0.499,-0.335,-0.015,1.0,1.0,1.0,1.0,1.0,0.0,35.0,0.0,2.0,2.0,5.0,0.0,0.0,0.0,0.0,1.0,0.0
11,0.517,-0.580,0.821,-1.144,0.066,-0.289,-0.603,-1.159,0.0,1.0,1.0,0.0,1.0,0.0,26.0,0.0,4.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0
13,1.392,0.584,0.930,0.064,-0.742,-0.477,-0.145,0.036,1.0,0.0,1.0,1.0,1.0,1.0,30.0,0.0,3.0,2.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0
15,-1.149,-1.276,-0.395,-0.905,1.423,-0.059,-0.522,-0.813,1.0,1.0,1.0,1.0,0.0,0.0,70.0,0.0,4.0,2.0,6.0,0.0,0.0,0.0,0.0,1.0,0.0
18,0.553,0.232,0.438,0.146,0.435,-1.103,-0.484,-0.652,0.0,0.0,0.0,1.0,0.0,0.0,57.0,0.0,4.0,2.0,5.0,0.0,0.0,0.0,0.0,1.0,1.0
19,0.233,0.703,-0.536,-0.335,-2.734,-1.853,2.068,0.571,1.0,1.0,1.0,0.0,0.0,0.0,42.0,1.0,4.0,3.0,5.0,0.0,0.0,1.0,1.0,1.0,1.0
20,0.837,1.031,0.321,0.277,0.382,-0.297,-0.425,-0.402,0.0,0.0,1.0,1.0,0.0,0.0,36.0,0.0,4.0,3.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0
21,-1.053,-0.368,-1.015,0.391,-1.018,1.170,1.298,1.421,1.0,0.0,0.0,1.0,0.0,0.0,28.0,0.0,4.0,2.0,5.0,0.0,0.0,1.0,0.0,0.0,0.0
22,0.711,1.465,0.497,1.696,-1.119,-0.182,0.322,1.481,1.0,1.0,1.0,1.0,0.0,0.0,38.0,1.0,2.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.554,-0.447,0.954,-0.255,-0.182,-0.337,-0.494,-0.694,1.0,1.0,0.0,1.0,1.0,1.0,62.0,1.0,2.0,3.0,2.0,1.0,1.0,0.0,0.0,1.0,1.0
25,-0.431,0.004,-0.829,0.029,1.153,3.062,0.110,1.166,1.0,1.0,1.0,1.0,1.0,1.0,22.0,0.0,2.0,3.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0
26,1.020,0.870,0.462,0.394,-0.241,-0.072,-0.121,0.351,1.0,1.0,1.0,1.0,1.0,1.0,65.0,0.0,1.0,2.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0
27,0.498,-0.522,0.449,-0.862,0.382,-0.386,-0.523,-0.818,1.0,1.0,1.0,1.0,0.0,1.0,77.0,0.0,1.0,2.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0
28,-0.552,0.136,-0.877,0.630,-0.637,0.944,1.115,1.928,1.0,0.0,1.0,1.0,1.0,1.0,38.0,0.0,4.0,2.0,2.0,0.0,0.0,1.0,1.0,0.0,1.0

In [81]:
graph_data = total_data.copy()

In [82]:
machine_data = total_data.copy()

In [83]:

# List the columns you want to create dummy variables for
dummy_cols = ['HH_Income', 'HH_size', 'Edu_level']

# Convert these columns to string so that get_dummies treats them as categorical labels
machine_data[dummy_cols] = machine_data[dummy_cols].astype(str)

# Create dummy variables for these columns, dropping the first category for each to avoid multicollinearity
dummies = pd.get_dummies(machine_data[dummy_cols], prefix=dummy_cols, drop_first=True)

# Drop the original columns and concatenate the dummy variables with the rest of the data
machine_data = pd.concat([machine_data.drop(columns=dummy_cols), dummies], axis=1)

# Display the first few rows of the resulting DataFrame
print(machine_data.head())

   PA_mean  PA_std  WW_mean  WW_std  SW_mean  SW_std  NW_mean  NW_std  VWA  \
0    0.098   0.380    0.169   0.027    0.017   0.438   -0.131   0.492  1.0
3   -0.413  -0.480    0.692  -0.401   -0.026  -0.269   -0.572  -1.026  1.0
6   -2.204  -0.583   -3.575  -1.448   -2.333  -0.080    4.188   2.368  1.0
7   -0.903  -0.613    0.041   0.374   -0.053   0.352   -0.017   1.145  1.0
8   -1.074  -1.489   -0.464  -1.355    1.363  -0.126   -0.486  -0.661  1.0

   MWA  W/B  VRC  MRC  Gender   Age  US_born  Health_status  Arthritis  \
0  1.0  1.0  1.0  1.0     0.0  22.0      0.0            0.0        0.0
3  1.0  1.0  1.0  1.0     0.0  21.0      0.0            0.0        0.0
6  1.0  1.0  1.0  1.0     1.0  43.0      0.0            0.0        0.0
7  1.0  1.0  1.0  1.0     0.0  80.0      0.0            1.0        1.0
8  1.0  1.0  1.0  1.0     0.0  80.0      0.0            1.0        1.0

   Lose_weight  Excercise  Con_lost_weight  increase_exercise  HH_Income_16.0  \
0          1.0        0.0              1.0                1.0               0
3          0.0        0.0              0.0                0.0               0
6          0.0        0.0              1.0                1.0               0
7          1.0        1.0              1.0                1.0               0
8          0.0        0.0              0.0                1.0               0

   HH_Income_2.0  HH_Income_3.0  HH_Income_4.0  HH_Income_5.0  HH_size_2.0  \
0              0              0              1              0            0
3              0              0              0              0            0
6              1              0              0              0            0
7              0              1              0              0            1
8              0              0              0              0            0

   HH_size_3.0  Edu_level_2.0  Edu_level_3.0  Edu_level_4.0  Edu_level_5.0  \
0            1              0              0              0              1
3            1              0              0              0              0
6            0              0              1              0              0
7            0              0              0              1              0
8            0              0              1              0              0

   Edu_level_6.0
0              0
3              0
6              0
7              0
8              0

In [84]:
machine_data.head(20)

,PA_mean,PA_std,WW_mean,WW_std,SW_mean,SW_std,NW_mean,NW_std,VWA,MWA,W/B,VRC,MRC,Gender,Age,US_born,Health_status,Arthritis,Lose_weight,Excercise,Con_lost_weight,increase_exercise,HH_Income_16.0,HH_Income_2.0,HH_Income_3.0,HH_Income_4.0,HH_Income_5.0,HH_size_2.0,HH_size_3.0,Edu_level_2.0,Edu_level_3.0,Edu_level_4.0,Edu_level_5.0,Edu_level_6.0
0,0.098,0.380,0.169,0.027,0.017,0.438,-0.131,0.492,1.0,1.0,1.0,1.0,1.0,0.0,22.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0,0,0,1,0,0,1,0,0,0,1,0
3,-0.413,-0.480,0.692,-0.401,-0.026,-0.269,-0.572,-1.026,1.0,1.0,1.0,1.0,1.0,0.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,0,0,0
6,-2.204,-0.583,-3.575,-1.448,-2.333,-0.080,4.188,2.368,1.0,1.0,1.0,1.0,1.0,1.0,43.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0,1,0,0,0,0,0,0,1,0,0,0
7,-0.903,-0.613,0.041,0.374,-0.053,0.352,-0.017,1.145,1.0,1.0,1.0,1.0,1.0,0.0,80.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0,0,1,0,0,1,0,0,0,1,0,0
8,-1.074,-1.489,-0.464,-1.355,1.363,-0.126,-0.486,-0.661,1.0,1.0,1.0,1.0,1.0,0.0,80.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0,0,0,0,0,0,0,0,1,0,0,0
9,-1.320,-1.688,-1.747,-0.984,-1.255,-0.172,-0.609,-1.183,1.0,1.0,0.0,1.0,1.0,0.0,55.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0,0,0,1,0,1,0,0,0,0,1,0
10,0.356,0.293,0.413,0.612,0.135,-0.499,-0.335,-0.015,1.0,1.0,1.0,1.0,1.0,0.0,35.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,1,0,0,0,1,0,0,0,0,1,0
11,0.517,-0.580,0.821,-1.144,0.066,-0.289,-0.603,-1.159,0.0,1.0,1.0,0.0,1.0,0.0,26.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0,0,1,0,0,1,0,0,1,0,0
13,1.392,0.584,0.930,0.064,-0.742,-0.477,-0.145,0.036,1.0,0.0,1.0,1.0,1.0,1.0,30.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,0,1,0,0,1,0,0,0,1,0,0
15,-1.149,-1.276,-0.395,-0.905,1.423,-0.059,-0.522,-0.813,1.0,1.0,1.0,1.0,0.0,0.0,70.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,0,0,1,0,1,0,0,0,0,0,1
18,0.553,0.232,0.438,0.146,0.435,-1.103,-0.484,-0.652,0.0,0.0,0.0,1.0,0.0,0.0,57.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0,0,0,1,0,1,0,0,0,0,1,0
19,0.233,0.703,-0.536,-0.335,-2.734,-1.853,2.068,0.571,1.0,1.0,1.0,0.0,0.0,0.0,42.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0,0,0,1,0,0,1,0,0,0,1,0
20,0.837,1.031,0.321,0.277,0.382,-0.297,-0.425,-0.402,0.0,0.0,1.0,1.0,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0,0,0,1,0,0,1,1,0,0,0,0
21,-1.053,-0.368,-1.015,0.391,-1.018,1.170,1.298,1.421,1.0,0.0,0.0,1.0,0.0,0.0,28.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,0,1,0,1,0,0,0,0,1,0
22,0.711,1.465,0.497,1.696,-1.119,-0.182,0.322,1.481,1.0,1.0,1.0,1.0,0.0,0.0,38.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,1,0,0,1,0,0
23,0.554,-0.447,0.954,-0.255,-0.182,-0.337,-0.494,-0.694,1.0,1.0,0.0,1.0,1.0,1.0,62.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0,1,0,0,0,0,1,1,0,0,0,0
25,-0.431,0.004,-0.829,0.029,1.153,3.062,0.110,1.166,1.0,1.0,1.0,1.0,1.0,1.0,22.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,1,0,0,0,0,1,0,1,0,0,0
26,1.020,0.870,0.462,0.394,-0.241,-0.072,-0.121,0.351,1.0,1.0,1.0,1.0,1.0,1.0,65.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,0,0,0,1,0,1,0,0,0,0
27,0.498,-0.522,0.449,-0.862,0.382,-0.386,-0.523,-0.818,1.0,1.0,1.0,1.0,0.0,1.0,77.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0,0,0,0,0,1,0,0,0,0,0,0
28,-0.552,0.136,-0.877,0.630,-0.637,0.944,1.115,1.928,1.0,0.0,1.0,1.0,1.0,1.0,38.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0,0,0,1,0,1,0,1,0,0,0,0

In [85]:
%store machine_data

Stored 'machine_data' (DataFrame)

In [86]:
%store graph_data

Stored 'graph_data' (DataFrame)

In [87]:
# Creating the model with the training data and test the model with the testing data.
# create teh confustion matrix and calcualte the accuray and other metrics

In [88]:

obj_col = ['PA_mean', 'PA_std', 'WW_mean', 'WW_std', 'SW_mean', 'SW_std',
       'NW_mean', 'NW_std','Gender', 'Age',
       'US_born','HH_Income_16.0',
       'HH_Income_2.0', 'HH_Income_3.0', 'HH_Income_4.0', 'HH_Income_5.0',
       'HH_size_2.0', 'HH_size_3.0', 'Edu_level_2.0', 'Edu_level_3.0',
       'Edu_level_4.0', 'Edu_level_5.0', 'Edu_level_6.0']

In [89]:
sub_col = ['VWA', 'MWA', 'W/B', 'VRC', 'MRC', 'Gender', 'Age',
       'US_born','Arthritis', 'Lose_weight', 'Excercise',
       'Con_lost_weight', 'increase_exercise', 'HH_Income_16.0',
       'HH_Income_2.0', 'HH_Income_3.0', 'HH_Income_4.0', 'HH_Income_5.0',
       'HH_size_2.0', 'HH_size_3.0', 'Edu_level_2.0', 'Edu_level_3.0',
       'Edu_level_4.0', 'Edu_level_5.0', 'Edu_level_6.0']

In [90]:
target = 'Health_status'

In [91]:
obj_data = machine_data[obj_col + [target]].copy()

In [92]:
sub_data = machine_data[sub_col + [target]].copy()

In [96]:
machine_data.reset_index( drop= True, inplace = True )

In [98]:
obj_data.reset_index(drop= True, inplace= True)

In [99]:
obj_data.head()

,PA_mean,PA_std,WW_mean,WW_std,SW_mean,SW_std,NW_mean,NW_std,Gender,Age,US_born,HH_Income_16.0,HH_Income_2.0,HH_Income_3.0,HH_Income_4.0,HH_Income_5.0,HH_size_2.0,HH_size_3.0,Edu_level_2.0,Edu_level_3.0,Edu_level_4.0,Edu_level_5.0,Edu_level_6.0,Health_status
0,0.098,0.380,0.169,0.027,0.017,0.438,-0.131,0.492,0.0,22.0,0.0,0,0,0,1,0,0,1,0,0,0,1,0,0.0
1,-0.413,-0.480,0.692,-0.401,-0.026,-0.269,-0.572,-1.026,0.0,21.0,0.0,0,0,0,0,0,0,1,0,0,0,0,0,0.0
2,-2.204,-0.583,-3.575,-1.448,-2.333,-0.080,4.188,2.368,1.0,43.0,0.0,0,1,0,0,0,0,0,0,1,0,0,0,0.0
3,-0.903,-0.613,0.041,0.374,-0.053,0.352,-0.017,1.145,0.0,80.0,0.0,0,0,1,0,0,1,0,0,0,1,0,0,1.0
4,-1.074,-1.489,-0.464,-1.355,1.363,-0.126,-0.486,-0.661,0.0,80.0,0.0,0,0,0,0,0,0,0,0,1,0,0,0,1.0

In [100]:
sub_data.reset_index(drop= True, inplace= True)

In [102]:
%store sub_data

Stored 'sub_data' (DataFrame)

In [103]:
%store obj_data

Stored 'obj_data' (DataFrame)

In [104]:
# Till now, Stored sub_data, obj_data, merged_data and total_data in store functions.